require 'bunny'
require 'json'

require 'govuk_message_queue_consumer/version'
require 'govuk_message_queue_consumer/heartbeat_processor'
require 'govuk_message_queue_consumer/json_processor'
require 'govuk_message_queue_consumer/message'
require 'govuk_message_queue_consumer/message_consumer'
require 'govuk_message_queue_consumer/consumer'
require 'govuk_message_queue_consumer/rabbitmq_config'
