require 'govuk_message_queue_consumer/version'
require 'govuk_message_queue_consumer/heartbeat_processor'
require 'govuk_message_queue_consumer/message'
require 'govuk_message_queue_consumer/consumer'
